# -*- coding: utf-8 -*-
"""project_212935985_322999095

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pmhGkTNXyvNMOjLx7N5qfXsMivYN34f
"""

#1.1.5
import numpy as np
import scipy.stats as stats

#הגדרת פרמטרים
np.random.seed(42)
num_years = 100000
n_charges = 80

values = np.array([12, 3, 0, -4])
probs = np.array([1/6, 1/3, 1/6, 1/3])

#הגרלת נתונים
sim_data = np.random.choice(values, size=(num_years, n_charges), p=probs)

#חישוב סכום שנתי
annual_sums = sim_data.sum(axis=1)

#חישוב הסתברויות
p_positive_emp = np.mean(annual_sums > 0)
p_between_emp = np.mean((annual_sums >= 50) & (annual_sums <= 150))
c_emp = np.percentile(annual_sums, 10)

#חישוב ערכים
mu_x = np.sum(values * probs)
var_x = np.sum((values - mu_x)**2 * probs)
mu_s = n_charges * mu_x
sigma_s = np.sqrt(n_charges * var_x)

p_positive_theo = 1 - stats.norm.cdf(0, mu_s, sigma_s)
p_between_theo = stats.norm.cdf(150, mu_s, sigma_s) - stats.norm.cdf(50, mu_s, sigma_s)
c_theo = stats.norm.ppf(0.10, mu_s, sigma_s)

#הדפסת תוצאות
print("השוואת תוצאות: אנליטי מול סימולציה")
print(f"P(סכום > 0): תיאורטי = {p_positive_theo:.4f} | סימולציה = {p_positive_emp:.4f}")
print(f"P(50 <= סכום <= 150): תיאורטי = {p_between_theo:.4f} | סימולציה = {p_between_emp:.4f}")
print(f"ערך c עבור 90%: תיאורטי = {c_theo:.2f} | סימולציה = {c_emp:.2f}")

#גרף 1
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

#יצירת היסטוגרמה
plt.hist(annual_sums, bins=60, density=True, alpha=0.6, color='skyblue', edgecolor='black', label='Simulation')

#חישוב צפיפות
x_axis = np.linspace(mu_s - 4*sigma_s, mu_s + 4*sigma_s, 500)
clt_density = stats.norm.pdf(x_axis, mu_s, sigma_s)
plt.plot(x_axis, clt_density, color='red', linewidth=2.5, label='Theoretical CLT')

#סימון קו תוחלת
plt.axvline(mu_s, color='darkgreen', linestyle='--', linewidth=1.5, label=f'Mean ({mu_s:.2f})')

#עיצוב הגרף
plt.title('Graph 1: Distribution of Annual Charging Credits vs. CLT Approximation', fontsize=14, fontweight='bold')
plt.xlabel('Annual Sum of Credits (NIS)', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(fontsize=11)

plt.show()

#2.2.1
import numpy as np

#הגדרת פרמטרים אקראיים
np.random.seed(39)
a = np.random.uniform(2, 12)
r = np.random.randint(1, 5)

#יצירת וקטור נקודות
x_grid = np.linspace(-r, a + r, 300)

#הגדרת פונקציית צפיפות
def my_pdf(x, a):
    conds = [x <= 0, (x > 0) & (x < a), x >= a]
    funcs = [0, lambda x: (3 * x**2) / (a**3), 0]
    return np.piecewise(x, conds, funcs)

#הגדרת פונקציית התפלגות מצטברת
def my_cdf(x, a):
    conds = [x < 0, (x >= 0) & (x <= a), x > a]
    funcs = [0, lambda x: (x / a)**3, 1]
    return np.piecewise(x, conds, funcs)

#חישוב הערכים
pdf_vals = my_pdf(x_grid, a)
cdf_vals = my_cdf(x_grid, a)

#גרף 2
import matplotlib.pyplot as plt

#יצירת מערך גרפים זה לצד זה
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

#שרטוט גרף הצפיפות
axes[0].plot(x_grid, pdf_vals, color='blue', linewidth=2, label='PDF f(x;a)')
axes[0].axvline(0, color='gray', linestyle='--', linewidth=1.5, label='x=0')
axes[0].axvline(a, color='red', linestyle='--', linewidth=1.5, label=f'x=a ({a:.2f})')
axes[0].set_title('Probability Density Function (PDF)', fontsize=12, fontweight='bold')
axes[0].set_xlabel('x', fontsize=10)
axes[0].set_ylabel('Density', fontsize=10)
axes[0].grid(True, linestyle='--', alpha=0.5)
axes[0].legend()

#שרטוט גרף ההתפלגות המצטברת
axes[1].plot(x_grid, cdf_vals, color='green', linewidth=2, label='CDF F(x;a)')
axes[1].axvline(0, color='gray', linestyle='--', linewidth=1.5, label='x=0')
axes[1].axvline(a, color='red', linestyle='--', linewidth=1.5, label=f'x=a ({a:.2f})')
axes[1].set_title('Cumulative Distribution Function (CDF)', fontsize=12, fontweight='bold')
axes[1].set_xlabel('x', fontsize=10)
axes[1].set_ylabel('Cumulative Probability', fontsize=10)
axes[1].grid(True, linestyle='--', alpha=0.5)
axes[1].legend()

plt.tight_layout()
plt.show()

#2.2
import numpy as np

def estimate_mom(x):
    # Method-of-Moments estimator for a
    return (4 / 3) * np.mean(x)

def estimate_mle(x):
    # Maximum-Likelihood estimator for a
    return np.max(x)

def estimate_unbiased(x):
    # Unbiased estimator for a
    n = len(x)
    return ((3 * n + 1) / (3 * n)) * np.max(x)

def estimate_max_2x(x):
    # Naive estimator: 2 * max(x)
    return 2 * np.max(x)

#2.3
import numpy as np

def my_pdf(x, a):
    return np.where((x > 0) & (x < a), (3 * x**2) / (a**3), 0)

def inv_cdf(u, a):
    return a * (u ** (1/3))

def sample_from_f(n, a):
    u = np.random.uniform(0, 1, n)
    return inv_cdf(u, a)

#גרף 3
import matplotlib.pyplot as plt

# קביעת גדלי המדגמים
sample_sizes = [100, 1000, 50000]

# פתיחת 3 פאנלים צמודים (גרף 3: שורה אחת, 3 עמודות)
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# יצירת ציר ה-x עבור קו ה-PDF התאורטי
x_grid_g3 = np.linspace(-r, a + r, 300)
pdf_values = my_pdf(x_grid_g3, a)

# לולאה שרצה על גדלי המדגמים ומציירת כל פאנל בנפרד
for i, n in enumerate(sample_sizes):
    ax = axes[i]

    # 1. הגרלת הנתונים בעזרת הקוד מחלק 1
    samples = sample_from_f(n, a)

    # 2. ציור ההיסטוגרמה האמפירית המנורמלת
    ax.hist(samples, bins=30, density=True, alpha=0.6, color='skyblue', edgecolor='black', label='Empirical')

    # 3. הוספת קו הצפיפות התאורטי מעל
    ax.plot(x_grid_g3, pdf_values, 'r-', lw=2, label='Theoretical PDF')

    # עיצוב, כותרות ותוויות לכל פאנל
    ax.set_title(f'n = {n}')
    ax.set_xlabel('x')
    ax.set_ylabel('Density')
    ax.legend(loc='upper left')

# התאמת המרווחים והצגת הגרף
plt.tight_layout()
plt.show()

#2.4 + גרף 4
import numpy as np
import matplotlib.pyplot as plt

def inv_cdf(u, a):
    # הפונקציה ההופכית ל-CDF שנגזרה אנליטית
    return a * (u ** (1/3))

def sample_from_f(n, a):
    # הגרלת n מדגמי IID בשיטת הטרנספורמציה ההופכית
    u = np.random.uniform(0, 1, n)
    return inv_cdf(u, a)

def estimate_mom(x):
    # אומד מומנטים (MoM) ל-a
    return (4 / 3) * np.mean(x)

def estimate_mle(x):
    # אומד נראות מקסימלית (MLE) ל-a
    return np.max(x)

def estimate_unbiased(x):
    # אומד חסר הטיה ל-a
    n = len(x)
    return ((3 * n + 1) / (3 * n)) * np.max(x)

def estimate_max_2x(x):
    # אומד נאיבי (פעמיים המקסימום)
    return 2 * np.max(x)

def calculate_estimators_progression(sample, n_values):
    # חישוב ארבעת האומדנים עבור תתי-מדגמים בגדלים משתנים
    estimates = {
        'MoM': [], 'MLE': [], 'Unbiased': [], 'Max_2x': []
    }
    for n in n_values:
        current_sample = sample[:n]
        estimates['MoM'].append(estimate_mom(current_sample))
        estimates['MLE'].append(estimate_mle(current_sample))
        estimates['Unbiased'].append(estimate_unbiased(current_sample))
        estimates['Max_2x'].append(estimate_max_2x(current_sample))
    return estimates

def plot_estimators_convergence(a_true=10, n_max=200):
    # הגרלת מדגם והפקת גרף 4 להצגת התכנסות האומדנים
    n_values = np.arange(5, n_max + 1, 5)
    full_sample = sample_from_f(n_max, a_true)
    estimates_dict = calculate_estimators_progression(full_sample, n_values)

    plt.figure(figsize=(10, 6))
    plt.plot(n_values, estimates_dict['MoM'], label='MoM', color='blue', linewidth=2)
    plt.plot(n_values, estimates_dict['MLE'], label='MLE', color='orange', linewidth=2)
    plt.plot(n_values, estimates_dict['Unbiased'], label='Unbiased', color='green', linewidth=2)
    plt.plot(n_values, estimates_dict['Max_2x'], label='Max_2x (Naive)', color='red', linewidth=2)

    # קו אופקי לערך האמיתי
    plt.axhline(y=a_true, color='black', linestyle='--', linewidth=2, label='True value of a')

    plt.title('Convergence of Estimators as Sample Size (n) Increases')
    plt.xlabel('Sample Size (n)')
    plt.ylabel('Estimated Value of a')
    plt.legend(loc='upper right')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

plot_estimators_convergence(a_true=a, n_max=200)

#2.5
import numpy as np

def inv_cdf(u, a):
    # טרנספורמציה הופכית אנליטית
    return a * (u ** (1/3))

def sample_from_f(n, a):
    # הגרלת n מדגמי IID
    u = np.random.uniform(0, 1, n)
    return inv_cdf(u, a)

def estimate_mom(x):
    # אומד מומנטים
    return (4 / 3) * np.mean(x)

def estimate_mle(x):
    # אומד נראות מקסימלית
    return np.max(x)

def estimate_unbiased(x):
    # אומד חסר הטיה
    n = len(x)
    return ((3 * n + 1) / (3 * n)) * np.max(x)

def estimate_max_2x(x):
    # אומד נאיבי
    return 2 * np.max(x)

def run_mse_simulation(a_true, K=200):
    # סימולציית חישוב שגיאות ריבועיות (MSE ו-RMSE) לפי גדלי מדגם משתנים
    n_values = np.arange(10, 151, 10)

    results = {
        'MSE': {m: [] for m in ['MoM', 'MLE', 'Unbiased', 'Max_2x']},
        'RMSE': {m: [] for m in ['MoM', 'MLE', 'Unbiased']}
    }

    for n in n_values:
        estimates = {m: [] for m in ['MoM', 'MLE', 'Unbiased', 'Max_2x']}

        # הרצת K סימולציות בלתי תלויות
        for _ in range(K):
            sample = sample_from_f(n, a_true)
            estimates['MoM'].append(estimate_mom(sample))
            estimates['MLE'].append(estimate_mle(sample))
            estimates['Unbiased'].append(estimate_unbiased(sample))
            estimates['Max_2x'].append(estimate_max_2x(sample))

        # חישוב מדדי הטעות לכל אומד
        for m in estimates.keys():
            mse = np.mean((np.array(estimates[m]) - a_true) ** 2)
            results['MSE'][m].append(mse)
            if m != 'Max_2x':
                results['RMSE'][m].append(np.sqrt(mse))

    return n_values, results

#גרף 5,6
import matplotlib.pyplot as plt

def plot_mse_and_rmse_results(n_values, results):
    # --- גרף 5: ניתוח MSE לכל האומדנים בסקלה לוגריתמית ---
    plt.figure(figsize=(10, 5))
    plt.plot(n_values, results['MSE']['MoM'], label='MoM', color='blue', marker='o')
    plt.plot(n_values, results['MSE']['MLE'], label='MLE', color='orange', marker='s')
    plt.plot(n_values, results['MSE']['Unbiased'], label='Unbiased', color='green', marker='^')
    plt.plot(n_values, results['MSE']['Max_2x'], label='Max_2x (Naive)', color='red', marker='x')

    plt.yscale('log')
    plt.title('Graph 5: MSE of Estimators as a Function of n (Log Scale)')
    plt.xlabel('Sample Size (n)')
    plt.ylabel('Mean Squared Error (MSE)')
    plt.grid(True, which="both", alpha=0.3)
    plt.legend(loc='upper right')
    plt.tight_layout()
    plt.show()

    # --- גרף 6: ניתוח RMSE לשלושת האומדנים המובילים ---
    plt.figure(figsize=(10, 5))
    plt.plot(n_values, results['RMSE']['MoM'], label='MoM', color='blue', marker='o')
    plt.plot(n_values, results['RMSE']['MLE'], label='MLE', color='orange', marker='s')
    plt.plot(n_values, results['RMSE']['Unbiased'], label='Unbiased', color='green', marker='^')

    plt.title('Graph 6: RMSE of Main Estimators as a Function of n')
    plt.xlabel('Sample Size (n)')
    plt.ylabel('Root Mean Squared Error (RMSE)')
    plt.grid(True, alpha=0.3)
    plt.legend(loc='upper right')
    plt.tight_layout()
    plt.show()

n_vals, sim_results = run_mse_simulation(a_true=a, K=200)
plot_mse_and_rmse_results(n_vals, sim_results)

# גרף 7
import numpy as np
import matplotlib.pyplot as plt

def run_bias_variance_decomposition(a_true, K=200):
    n_values = np.arange(10, 151, 10)

    # מיפוי פונקציות האומדים
    funcs = {
        'MoM': estimate_mom,
        'MLE': estimate_mle,
        'Unbiased': estimate_unbiased,
        'Max_2x': estimate_max_2x
    }

    # אתחול מילון המדדים לכל אומד
    metrics = {
        name: {'MSE': [], 'Var': [], 'Bias2': []}
        for name in funcs
    }

    for n_sample in n_values:
        estimates = {name: [] for name in funcs}

        # הרצת K סימולציות
        for _ in range(K):
            sample = sample_from_f(n_sample, a_true)
            for name, func in funcs.items():
                estimates[name].append(func(sample))

        # חישוב המדדים הסטטיסטיים
        for name in funcs:
            est = np.asarray(estimates[name])
            mean_est = est.mean()

            mse = np.mean((est - a_true) ** 2)
            variance = np.mean((est - mean_est) ** 2)
            bias2 = (mean_est - a_true) ** 2

            metrics[name]['MSE'].append(mse)
            metrics[name]['Var'].append(variance)
            metrics[name]['Bias2'].append(bias2)

    return n_values, metrics

# הרצת הסימולציה עם ה-a המקורקע מה-seed
np.random.seed(43)
n_values_decomp, decomposition = run_bias_variance_decomposition(a_true=a, K=200)

# שליפת נתוני ה-MLE עבור גרף 7
mle_metrics = decomposition['MLE']

# הדפסת בדיקת שפיות ל-MSE
print("\nפירוק MSE = Var + Bias^2 (דוגמה ל-MLE):")
for idx in [0, -1]:
    print(
        f"n={n_values_decomp[idx]} | "
        f"MSE={mle_metrics['MSE'][idx]:.6f}, "
        f"Var+Bias2={mle_metrics['Var'][idx] + mle_metrics['Bias2'][idx]:.6f}"
    )

# יצירת גרף 7 (פירוק להטיה ושונות)
plt.figure(figsize=(10, 6))
plt.plot(n_values_decomp, mle_metrics['MSE'], label='MSE', color='black', linewidth=3)
plt.plot(n_values_decomp, mle_metrics['Var'], label='Variance', color='blue', linewidth=2, linestyle='--')
plt.plot(n_values_decomp, mle_metrics['Bias2'], label='Bias^2', color='red', linewidth=2, linestyle=':')

# עיצוב והצגת הגרף
plt.title('Graph 7: Bias-Variance Decomposition for MLE Estimator')
plt.xlabel('Sample Size (n)')
plt.ylabel('Error Value')
plt.grid(True, alpha=0.3)
plt.legend(loc='upper right')
plt.tight_layout()

# שמירה והצגת הגרף על המסך
plt.savefig('graph_07.png', dpi=180, bbox_inches='tight')
plt.show()
plt.close()

#3.1
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

#נתוני הבעיה
mu_0 = 42
sigma = 8
n = 50
M = 1000
x_bar_sample = 39.8

# חישוב ה-p-value האמיתי של המדגם (pv)
Z_sample = (x_bar_sample - mu_0) / (sigma / np.sqrt(n))
pv = stats.norm.cdf(Z_sample)

#  הגרלת 1000 מדגמים תחת השערת האפס (H0)
np.random.seed(42) # קיבוע הגרעין לשחזור התוצאות
samples = np.random.normal(loc=mu_0, scale=sigma, size=(M, n))

sample_means = samples.mean(axis=1)
Z_stats = (sample_means - mu_0) / (sigma / np.sqrt(n))
# מדובר במבחן חד-צדדי שמאלי
p_values = stats.norm.cdf(Z_stats)


alphas = [0.01, pv, 0.05, 0.1, 0.2]
rejections = []

for alpha in alphas:

    num_rejections = np.sum(p_values < alpha)
    rejections.append(num_rejections)

alphas_sorted, rejections_sorted = zip(*sorted(zip(alphas, rejections)))

#גרף 8
plt.figure(figsize=(8, 5))

# יצירת העמודות
bars = plt.bar([f"{a:.4f}" for a in alphas_sorted],
               rejections_sorted,
               color='skyblue',
               edgecolor='black')

# עיצוב הגרף: תוויות וכותרת
plt.xlabel(r"Significance Level ($\alpha$)")
plt.ylabel("Number of Rejections")
plt.title("Graph 8: Number of Rejections out of 1000 Samples per $\\alpha$")
plt.grid(axis='y', linestyle='--', alpha=0.7)

# תוספת אופציונלית ומומלצת: הוספת מספר הדחיות המדויק מעל כל עמודה
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 10, int(yval), ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

#גרף 9
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# נתוני המדגם האמיתי
data = np.array([82.9, 70.8, 70.8, 82.5, 76.7, 71.4, 75.6, 59.6, 73.9, 69.2,
                 69.2, 76.0, 69.2, 77.5, 82.1, 62.9, 66.3, 74.4, 65.6, 68.6,
                 60.8, 74.8, 64.7, 73.1, 68.7, 62.8, 72.8, 70.8])

# חישוב ממוצע ואומד שונות בלתי מוטה
n = len(data)
mean_x = np.mean(data)
std_s = np.std(data, ddof=1) # חלוקה ב-27 כדי לקבל אומד בלתי מוטה

mu_0 = 75
alpha = 0.05

# ביצוע מבחן t למדגם יחיד
t_stat, p_val = stats.ttest_1samp(data, mu_0)

# חישוב רווח סמך 95 אחוזים
t_crit = stats.t.ppf(1 - alpha/2, df=n-1)
margin_error = t_crit * (std_s / np.sqrt(n))
ci_lower = mean_x - margin_error
ci_upper = mean_x + margin_error

print("ממוצע המדגם:", mean_x)
print("סטיית תקן מדגמית (אומדן):", std_s)
print("סטטיסטי המבחן:", t_stat)
print("ערך המובהקות:", p_val)
print("רווח סמך 95 אחוזים לתוחלת:", ci_lower, ci_upper)

# סימולציה - הגדרת משתנים
np.random.seed(42) # קיבוע הגרלה כדי שהתוצאות יחזרו על עצמן
M = 2000 # מספר המדגמים
n_sim = 28 # גודל כל מדגם

# שלב א - אומדן לטעות מסוג ראשון (אלפא)
samples_H0 = np.random.normal(loc=75, scale=std_s, size=(M, n_sim))
t_stats_H0, p_vals_H0 = stats.ttest_1samp(samples_H0, mu_0, axis=1)
reject_H0 = p_vals_H0 < alpha
alpha_hat = np.mean(reject_H0)

# שלב ב - אומדן לטעות מסוג שני (בטא)
samples_H1 = np.random.normal(loc=73, scale=std_s, size=(M, n_sim))
t_stats_H1, p_vals_H1 = stats.ttest_1samp(samples_H1, mu_0, axis=1)
accept_H0 = p_vals_H1 >= alpha
beta_hat = np.mean(accept_H0)

# שלב ג - רווחי סמך לאמידות בעזרת קירוב נורמלי למשתנה בינומי
z_95 = stats.norm.ppf(0.975)

# רווח סמך לאלפא
alpha_ci_margin = z_95 * np.sqrt((alpha_hat * (1 - alpha_hat)) / M)
alpha_ci_lower = alpha_hat - alpha_ci_margin
alpha_ci_upper = alpha_hat + alpha_ci_margin

# רווח סמך לבטא
beta_ci_margin = z_95 * np.sqrt((beta_hat * (1 - beta_hat)) / M)
beta_ci_lower = beta_hat - beta_ci_margin
beta_ci_upper = beta_hat + beta_ci_margin

# תוצאות הסימולציה
print("\nאומדן לטעות מסוג ראשון (אלפא):", alpha_hat)
print("רווח סמך 95 אחוזים לאלפא:", alpha_ci_lower, alpha_ci_upper)
print("אומדן לטעות מסוג שני (בטא):", beta_hat)
print("רווח סמך 95 אחוזים לבטא:", beta_ci_lower, beta_ci_upper)

# גרף 9 - יצירת הפאנלים
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
t_crit_val = stats.t.ppf(1 - alpha/2, df=n_sim-1)

# פאנל 1 - התפלגות סטטיסטי המבחן תחת השערת האפס
axes[0].hist(t_stats_H0, bins=50, color='skyblue', edgecolor='black', density=True)
axes[0].axvline(t_crit_val, color='red', linestyle='--')
axes[0].axvline(-t_crit_val, color='red', linestyle='--')
axes[0].set_title(f"H0: mu=75 (Type I Error)\nReject Rate: {alpha_hat:.3f}")
axes[0].set_xlabel("t-statistic")
axes[0].set_ylabel("Density")

# פאנל 2 - התפלגות סטטיסטי המבחן תחת ההשערה החלופית
axes[1].hist(t_stats_H1, bins=50, color='lightgreen', edgecolor='black', density=True)
axes[1].axvline(t_crit_val, color='red', linestyle='--')
axes[1].axvline(-t_crit_val, color='red', linestyle='--')
axes[1].set_title(f"H1: mu=73 (Type II Error)\nAccept Rate: {beta_hat:.3f}")
axes[1].set_xlabel("t-statistic")
axes[1].set_ylabel("Density")

plt.tight_layout()
plt.show()

#3.3
import numpy as np
import scipy.stats as stats

# הזנת נתוני הטווחים מהטבלה
premium = np.array([412, 388, 425, 401, 432, 395, 418, 405, 396, 422, 410, 398])
non_premium = np.array([385, 379, 398, 382, 410, 386, 395, 388, 380, 405, 392, 384])

# חישוב הפרשים ומדדים מדגמיים
differences = premium - non_premium
n = len(differences)
mean_diff = np.mean(differences)
std_diff = np.std(differences, ddof=1)
se_diff = std_diff / np.sqrt(n)

# הדפסת מדדי המדגם
print(f"הפרשים: {differences}")
print(f"ממוצע ההפרשים: {mean_diff:.4f}")
print(f"סטיית תקן של ההפרשים: {std_diff:.4f}")

# חישוב ידני של סטטיסטי המבחן וערך ה-p-value
t_stat_manual = mean_diff / se_diff
p_val_manual = 1 - stats.t.cdf(t_stat_manual, df=n-1)

# הדפסת תוצאות המבחן הידני
print(f"סטטיסטי מבחן t ידני: {t_stat_manual:.4f}")
print(f"p-value ידני: {p_val_manual:.7f}")

# חישוב גבול תחתון לרווח סמך 95%
t_crit = stats.t.ppf(0.95, df=n-1)
L = mean_diff - t_crit * se_diff
print(f"רווח סמך חד צדדי תחתון 95%: mu_D > {L:.4f}")

# אימות התוצאות באמצעות הפונקציה המובנית של scipy
res = stats.ttest_rel(premium, non_premium, alternative='greater')

# הדפסת תוצאות האימות
print(f"סטטיסטי מבחן t של scipy: {res.statistic:.4f}")
print(f"p-value של scipy: {res.pvalue:.7f}")
print(f"האם התוצאות זהות? {np.isclose(t_stat_manual, res.statistic)}")

#גרף 10
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 4.1 ייבוא וניקוי דאטה
df = pd.read_csv('ev_data.csv')
print(f"צורת הדאטה המקורי: {df.shape}")

# יצירת עמודת טווח נקייה
df['range_km_clean'] = df['range_km'].fillna(df['range_miles'] * 1.609344)

# יצירת עמודת סוללה נקייה
df['battery_kwh_clean'] = df['battery_kwh'].fillna(df['battery_wh'] / 1000)

# יצירת עמודת זמן טעינה נקייה
df['charge_time_min_clean'] = df['charge_time_min'].fillna(df['charge_time_hours'] * 60)

# וידאו שאין ערכים חסרים
print("ערכים חסרים בעמודות החדשות:")
print(df[['range_km_clean', 'battery_kwh_clean', 'charge_time_min_clean']].isna().sum())

# בדיקת שפיות וזיהוי חריגים
range_outliers = df[(df['range_km_clean'] < 100) | (df['range_km_clean'] > 700)]
battery_outliers = df[(df['battery_kwh_clean'] < 30) | (df['battery_kwh_clean'] > 120)]
charge_outliers = df[(df['charge_time_min_clean'] < 8) | (df['charge_time_min_clean'] > 240)]

print(f"מספר חריגים בטווח: {len(range_outliers)}")
print(f"מספר חריגים בסוללה: {len(battery_outliers)}")
print(f"מספר חריגים בזמן טעינה: {len(charge_outliers)}")

# 4.2 סטטיסטיקה תיאורית
cols = ['range_km_clean', 'battery_kwh_clean', 'charge_time_min_clean']
stats_summary = df[cols].describe(percentiles=[0.25, 0.5, 0.75])
print("\nטבלת סטטיסטיקה תיאורית:")
print(stats_summary)

# הפקת גרף 10: שלוש היסטוגרמות צמודות
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
titles = ['Range (km)', 'Battery Capacity (kWh)', 'Charge Time (min)']

for i, col in enumerate(cols):
    axes[i].hist(df[col], bins=50, color='lightblue', edgecolor='black', alpha=0.7)
    mean_val = df[col].mean()
    axes[i].axvline(mean_val, color='red', linestyle='--', linewidth=2, label=f'Mean: {mean_val:.2f}')
    axes[i].set_title(titles[i])
    axes[i].set_xlabel('Value')
    axes[i].set_ylabel('Frequency')
    axes[i].legend()

plt.tight_layout()
plt.show()

#גרף 11
import numpy as np
import matplotlib.pyplot as plt

# מימוש ידני של פונקציית היסטוגרמה
def hist_of_means(arr, n):
    arr = np.asarray(arr)
    min_val, max_val = np.min(arr), np.max(arr)

  # הגנה מפני מקרה שבו כל הערכים זהים (חלוקה באפס)
    if min_val == max_val:
        edges = np.linspace(min_val - 1, max_val + 1, n + 1)
        counts = np.zeros(n, dtype=int)
        counts[0] = len(arr)
        return counts, edges

    # יצירת n + 1 גבולות שווי מרחק
    edges = np.linspace(min_val, max_val, n + 1)
    counts = np.zeros(n, dtype=int)

    # שיוך כל ערך ל-bin המתאים
    for val in arr:
        if val == max_val:
            counts[-1] += 1
        else:
            bin_idx = int((val - min_val) / (max_val - min_val) * n)
            if 0 <= bin_idx < n:
                counts[bin_idx] += 1

    return counts, edges

# 1. הרצת הפונקציה הידנית על נתוני הטווח
my_counts, my_edges = hist_of_means(df['range_km_clean'], 30)

# 2. הרצה בעזרת הפונקציה המובנית של numpy להשוואה
np_counts, np_edges = np.histogram(df['range_km_clean'], bins=30)

# בדיקה האם התוצאות זהות
all_counts_equal = np.array_equal(my_counts, np_counts)
all_edges_close = np.allclose(my_edges, np_edges)
print(f"האם המונים זהים לחלוטין? {all_counts_equal}")
print(f"האם הגבולות זהים (בדיוק נומרי)? {all_edges_close}")

# 3. הפקת גרף 11: פאנלים זה לצד זה
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# פאנל שמאל: היסטוגרמה ידנית בעזרת plt.bar
bin_centers = (my_edges[:-1] + my_edges[1:]) / 2
bin_width = my_edges[1] - my_edges[0]
axes[0].bar(bin_centers, my_counts, width=bin_width, color='teal', edgecolor='black', alpha=0.7)
axes[0].set_title("Manual Histogram (plt.bar)")
axes[0].set_xlabel("Range (km)")
axes[0].set_ylabel("Count")

# פאנל ימין: היסטוגרמה מובנית בעזרת plt.hist
axes[1].hist(df['range_km_clean'], bins=30, color='coral', edgecolor='black', alpha=0.7)
axes[1].set_title("Built-in Histogram (plt.hist)")
axes[1].set_xlabel("Range (km)")

plt.tight_layout()
plt.show()

#גרף 12+13
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

# חישוב ממוצע וסטיית תקן
mean_range = df['range_km_clean'].mean()
std_range = df['range_km_clean'].std(ddof=1)

print(f"ממוצע המדגם: {mean_range:.4f}")
print(f"סטיית תקן בלתי מוטה: {std_range:.4f}")

# חישוב האחוזון ה-95 האמפירי והתאורטי
pct_95_empirical = np.percentile(df['range_km_clean'], 95)
pct_95_theoretical = stats.norm.ppf(0.95, loc=mean_range, scale=std_range)

print(f"אחוזון 95 אמפירי (מהדאטה): {pct_95_empirical:.4f}")
print(f"אחוזון 95 תאורטי (מהנורמלית): {pct_95_theoretical:.4f}")
print(f"הפרש בין האחוזונים: {abs(pct_95_empirical - pct_95_theoretical):.4f}")

# הפקת גרף 12: היסטוגרמה מנורמלת עם PDF נורמלי
plt.figure(figsize=(8, 5))
plt.hist(df['range_km_clean'], bins=50, density=True, color='skyblue', edgecolor='black', alpha=0.7)
x_vals = np.linspace(df['range_km_clean'].min(), df['range_km_clean'].max(), 300)
pdf_vals = stats.norm.pdf(x_vals, loc=mean_range, scale=std_range)
plt.plot(x_vals, pdf_vals, color='red', linewidth=2, label='Normal PDF')
plt.title('Graph 12: Normalized Histogram with Normal PDF')
plt.xlabel('Range (km)')
plt.ylabel('Density')
plt.legend()
plt.show()

# הפקת גרף 13: Q-Q Plot
plt.figure(figsize=(8, 5))
stats.probplot(df['range_km_clean'], dist="norm", plot=plt)
plt.title('Graph 13: Q-Q Plot')
plt.show()

#4.5
import pandas as pd
import numpy as np
import scipy.stats as stats

df = pd.read_csv('ev_data.csv')

# השלמת ערכים חסרים בעמודת הטווח לפי המרה מיילים לקילומטרים
df['range_km_clean'] = df['range_km'].fillna(df['range_miles'] * 1.609344)

# סינון הנתונים עבור שנתוני הייצור 2020 ו-2024
df_2020 = df[df['production_year'] == 2020].dropna(subset=['range_km_clean'])
df_2024 = df[df['production_year'] == 2024].dropna(subset=['range_km_clean'])

# ביצוע מבחן טי וולץ חד צדדי למדגמים בלתי תלויים
t_stat, p_val = stats.ttest_ind(df_2024['range_km_clean'], df_2020['range_km_clean'], alternative='greater', equal_var=False)

# חישוב גודל המדגמים, הממוצעים והשנויות
n_2020, n_2024 = len(df_2020), len(df_2024)
mean_2020, mean_2024 = df_2020['range_km_clean'].mean(), df_2024['range_km_clean'].mean()
var_2020, var_2024 = df_2020['range_km_clean'].var(), df_2024['range_km_clean'].var()

# חישוב דרגות חופש לפי נוסחת וולץ סאטרתווייט
df_welch = ((var_2024/n_2024 + var_2020/n_2020)**2) / (((var_2024/n_2024)**2 / (n_2024 - 1)) + ((var_2020/n_2020)**2 / (n_2020 - 1)))

# חישוב רווח סמך 95 אחוז דו צדדי להפרש הממוצעים
diff_mean = mean_2024 - mean_2020
se_welch = np.sqrt((var_2024 / n_2024) + (var_2020 / n_2020))
t_crit = stats.t.ppf(0.975, df=df_welch)
ci_lower = diff_mean - t_crit * se_welch
ci_upper = diff_mean + t_crit * se_welch

# הדפסת ערכי הפלט הסופיים של המבחן הסטטיסטי ורווח הסמך
print(f"T-statistic: {t_stat:.4f}, P-value: {p_val:.4f}")
print(f"95% Welch Confidence Interval: [{ci_lower:.4f}, {ci_upper:.4f}]")

#גרף 14
import pandas as pd
import matplotlib.pyplot as plt

# טעינת קובץ הנתונים שהועלה מראש לחלונית הקבצים
df = pd.read_csv('ev_data.csv')

# השלמת ערכים חסרים בעמודת הטווח לפי המרה מיילים לקילומטרים
df['range_km_clean'] = df['range_km'].fillna(df['range_miles'] * 1.609344)

# סינון הנתונים עבור שנתוני הייצור 2020 ו-2024
range_2020 = df[df['production_year'] == 2020]['range_km_clean'].dropna()
range_2024 = df[df['production_year'] == 2024]['range_km_clean'].dropna()

# יצירת דיאגרמת קופסה להשוואת התפלגות טווח הנסיעה בין השנתונים
plt.figure(figsize=(8, 6))
plt.boxplot([range_2020, range_2024], labels=['2020', '2024'], showmeans=True)

# הגדרת כותרות ושמות לצירים בעברית עבור הגרף
plt.title('Comparison of Electric Vehicle Range: 2020 vs 2024')
plt.xlabel('Production Year')
plt.ylabel('Range (km)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

#גרף 15
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# טעינת קובץ הנתונים שהועלה מראש לחלונית הקבצים
df = pd.read_csv('ev_data.csv')

# השלמת ערכים חסרים בעמודת זמן הטעינה לפי המרה של שעות לדקות
df['charge_time_min_clean'] = df['charge_time_min'].fillna(df['charge_time_hours'] * 60.0)

# חישוב ממוצע המדגם וסטיית התקן עבור עמודת זמן הטעינה הנקייה
mean_charge = df['charge_time_min_clean'].mean()
std_charge = df['charge_time_min_clean'].std()

# חישוב אומד נראות מקסימלית למדא לפי הופכי הממוצע שנגזר אנליטית
lambda_mle = 1.0 / mean_charge

# הדפסת מדדי הבדיקה האמפיריים והאומדן למסך
print(f"Sample Mean: {mean_charge:.4f}")
print(f"Sample Std: {std_charge:.4f}")
print(f"Lambda MLE: {lambda_mle:.4f}")

# יצירת גרף 15 הכולל היסטוגרמה מנורמלת וגרף צפיפות אקספוננציאלי תאורטי
plt.figure(figsize=(8, 6))
count, bins, ignored = plt.hist(df['charge_time_min_clean'], bins=50, density=True, alpha=0.6, color='skyblue', edgecolor='black')

# חישוב ערכי פונקציית הצפיפות התאורטית על פני טווח ערכי הבינים
x_axis = np.linspace(bins.min(), bins.max(), 500)
pdf_theoretical = lambda_mle * np.exp(-lambda_mle * x_axis)

# הוספת קו הצפיפות התאורטית באדום מעל ההיסטוגרמה המנורמלת
plt.plot(x_axis, pdf_theoretical, color='red', linewidth=2, label=f'Theoretical Exp(λ={lambda_mle:.4f})')

# הגדרת כותרות ושמות לצירים בעברית עבור הגרף
plt.title('Normalized Histogram of Charge Time with Theoretical Exponential PDF')
plt.xlabel('Charge Time (minutes)')
plt.ylabel('Density')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()

# גרף 16
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

# טעינת הנתונים וניקוי העמודה
df = pd.read_csv('ev_data.csv')
df['charge_time_min_clean'] = df['charge_time_min'].fillna(df['charge_time_hours'] * 60.0)

# הגדרת המשתנה החסר מתוך העמודה הנקייה
charge_data = df['charge_time_min_clean']
positive_charge = charge_data[charge_data > 0]

# 1. התאמת פרמטרים עבור שלוש ההתפלגויות
fit_exp = stats.expon.fit(positive_charge, floc=0)
fit_gamma = stats.gamma.fit(positive_charge)
fit_weibull = stats.weibull_min.fit(positive_charge, floc=0)

# 2. ביצוע מבחן Kolmogorov-Smirnov (KS) לטיב התאמה
ks_exp = stats.kstest(positive_charge, 'expon', args=fit_exp)
ks_gamma = stats.kstest(positive_charge, 'gamma', args=fit_gamma)
ks_weibull = stats.kstest(positive_charge, 'weibull_min', args=fit_weibull)

# הדפסת מדדי הטיב בדיוק לפי תבנית הדרישה
print(
    f"Exponential: D={ks_exp.statistic:.4f}, "
    f"p={ks_exp.pvalue:.4e}"
)

print(
    f"Gamma: D={ks_gamma.statistic:.4f}, "
    f"p={ks_gamma.pvalue:.4e}"
)

print(
    f"Weibull: D={ks_weibull.statistic:.4f}, "
    f"p={ks_weibull.pvalue:.4e}"
)

# 3. יצירת גרף 16
plt.figure(figsize=(10, 6))
_, bins, _ = plt.hist(positive_charge, bins=50, density=True, alpha=0.5, color='skyblue', edgecolor='black')
x_axis = np.linspace(bins.min(), bins.max(), 500)

# ציור קווי הצפיפות לגרף
plt.plot(x_axis, stats.expon.pdf(x_axis, *fit_exp), color='red', linewidth=2, label='Exponential')
plt.plot(x_axis, stats.weibull_min.pdf(x_axis, *fit_weibull), color='purple', linewidth=2, label='Weibull')

# עיצוב והצגת הגרף
plt.title('Graph 16: Exponential vs Weibull Fit for Charging Time')
plt.xlabel('Charge Time (minutes)')
plt.ylabel('Density')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

plt.savefig('graph_16.png', dpi=180, bbox_inches='tight')
plt.show()
plt.close()

# גרף 17 - חלק 4.7 בונוס
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

# טעינת הנתונים וניקוי
df = pd.read_csv('ev_data.csv')
df['range_km_clean'] = df['range_km'].fillna(df['range_miles'] * 1.609344)

# סינון לשנתוני 2020 ו-2024 בלבד
df_filtered = df[
    df['production_year'].isin([2020, 2024])
].dropna(subset=['range_km_clean'])

# חישוב והדפסת מדדי הקבוצות
groups_summary = df_filtered.groupby(
    ['is_premium', 'production_year']
)['range_km_clean'].agg(['mean', 'std', 'count'])

print("\n===== חלק 4.7 בונוס =====")
print(groups_summary)

# הפרדת הנתונים לארבע תת-קבוצות
g_0_2020 = df_filtered[
    (df_filtered['is_premium'] == 0) & (df_filtered['production_year'] == 2020)
]['range_km_clean']

g_0_2024 = df_filtered[
    (df_filtered['is_premium'] == 0) & (df_filtered['production_year'] == 2024)
]['range_km_clean']

g_1_2020 = df_filtered[
    (df_filtered['is_premium'] == 1) & (df_filtered['production_year'] == 2020)
]['range_km_clean']

g_1_2024 = df_filtered[
    (df_filtered['is_premium'] == 1) & (df_filtered['production_year'] == 2024)
]['range_km_clean']

group_dict = {
    'Non-Premium 2020': g_0_2020,
    'Non-Premium 2024': g_0_2024,
    'Premium 2020': g_1_2020,
    'Premium 2024': g_1_2024
}

# יצירת דיאגרמת קופסה משותפת
plt.figure(figsize=(10, 6))

plt.boxplot(list(group_dict.values()), labels=list(group_dict.keys()), showmeans=True)

plt.title('Graph 17: EV Range across Premium Status and Production Years')
plt.xlabel('Group Category')
plt.ylabel('Range (km)')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()

# שמירה והצגת הגרף
plt.savefig('graph_17.png', dpi=180, bbox_inches='tight')
plt.show()
plt.close()

# ביצוע מבחני t זוגיים עם תיקון בונפרוני
alpha_original = 0.05
num_comparisons = 6
alpha_bonf = alpha_original / num_comparisons

pairs = [
    ('Non-Premium 2020', 'Non-Premium 2024'),
    ('Non-Premium 2020', 'Premium 2020'),
    ('Non-Premium 2020', 'Premium 2024'),
    ('Non-Premium 2024', 'Premium 2020'),
    ('Non-Premium 2024', 'Premium 2024'),
    ('Premium 2020', 'Premium 2024')
]

print(f"\nBonferroni Corrected Alpha: {alpha_bonf:.6f}")

# הרצת המבחנים והדפסה לפי פורמט היעד
for group1, group2 in pairs:
    t_stat_pair, p_val_pair = stats.ttest_ind(
        group_dict[group1],
        group_dict[group2],
        equal_var=False
    )
    significant = p_val_pair < alpha_bonf
    print(
        f"{group1} vs {group2}: "
        f"t={t_stat_pair:.6f}, "
        f"p-value={p_val_pair:.6e}, "
        f"Significant={significant}"
    )

print("\nהקוד הסתיים בהצלחה.")
